@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\cad\iar\ewarm630\common\bin\cspybat" "D:\cad\iar\ewarm630\arm\bin\armproc.dll" "D:\cad\iar\ewarm630\arm\bin\armsim2.dll"  %1 --plugin "D:\cad\iar\ewarm630\arm\bin\armbat.dll" --macro "D:\cad\iar\ewarm630\arm\config\debugger\ST\Trace_STM32F1xx.dmac" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "D:\cad\iar\ewarm630\arm\CONFIG\debugger\ST\iostm32f10xxB.ddf" "--semihosting" "--device=STM32F103xB" 


